# Generated by Django 3.0.4 on 2020-03-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_novinky_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novinky',
            name='status',
            field=models.IntegerField(choices=[(0, 'Zahozeno'), (1, 'Publikováno')], default=0),
        ),
    ]
