# Generated by Django 3.0.4 on 2020-03-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200316_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novinky',
            name='foto',
        ),
    ]
