# Generated by Django 3.0.4 on 2020-03-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_novinky_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novinky',
            name='foto',
        ),
    ]
