# Generated by Django 3.0.4 on 2020-03-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200316_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novinky',
            options={'ordering': ['vytvoreno']},
        ),
    ]
