# Generated by Django 3.0.4 on 2020-03-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200316_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='novinky',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
