# Generated by Django 3.0.4 on 2020-03-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_novinky_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='novinky',
            name='foto2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='novinky',
            name='foto3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='novinky',
            name='foto4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='novinky',
            name='foto5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
