# Generated by Django 3.0.4 on 2020-03-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200316_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novinky',
            name='foto4',
        ),
        migrations.RemoveField(
            model_name='novinky',
            name='foto5',
        ),
    ]
