# Generated by Django 3.0.4 on 2020-03-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200316_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novinky',
            options={'ordering': ['-vytvoreno']},
        ),
    ]
