# Generated by Django 3.0.4 on 2020-03-16 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200316_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='novinky',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
