# Generated by Django 3.0.4 on 2020-03-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_novinky_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novinky',
            options={'ordering': ['-date']},
        ),
    ]
